name: social_network_app_mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
environment:
  sdk: ">=2.19.0-108.0.dev <3.0.0"
  # ">=3.0.0-35.0.dev <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  get_time_ago: ^1.2.0
  firebase_messaging: ^14.1.4
  firebase_core: ^2.4.0
  url_launcher: ^6.1.7
  transparent_image: ^2.0.0
  visibility_detector: ^0.3.3
  expandable_text: ^2.3.0
  flutter_linkify: ^5.0.2
  flutter_hooks: ^0.18.6
  percent_indicator: ^4.2.2
  badges: ^2.0.3
  preload_page_view: ^0.1.6
  comment_tree: ^0.3.0
  draggable_bottom_sheet: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  meta: ^1.7.0
  path: ^1.8.1
  uuid: ^3.0.6
  photo_manager: ^2.5.2
  camera: ^0.10.1
  flutter_cache_manager: ^3.0.2
  rxdart: ^0.27.2
  collection: ^1.15.0
  file_picker: ^5.2.5
  table_calendar: ^3.0.9
  carousel_slider: ^4.2.1
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_riverpod: ^2.1.3
  dio: ^4.0.6
  photo_view: ^0.14.0
  gallery_saver: ^2.3.2
  loader_overlay: ^2.1.0
  easy_debounce: ^2.0.3
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  mime: ^1.0.4
  flutter_video_info: ^1.3.1
  http_parser: ^4.0.2
  loader_skeleton: ^0.0.4
  shimmer: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_html: ^3.0.0-alpha.6
  flutter_secure_storage: ^8.0.0
  audioplayers: ^4.0.0
  hooks_riverpod: ^2.3.1
  flutter_launcher_icons: ^0.12.0
  flutter_page_indicator: ^0.0.3
  marquee: ^2.2.3
  image_picker: ^0.8.7
  full_screen_image: ^2.0.0
  flutter_map_location_marker: ^5.2.1
  gesture_x_detector: ^1.0.0
  # helpers: ^1.1.4
  http: ^0.13.4
  path_provider: ^2.0.6
  volume_watcher: ^2.0.1
  wakelock: ^0.6.1+2
  step_progress_indicator: ^1.0.2
  google_sign_in: ^6.0.2
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  flick_video_player: ^0.5.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_slidable: ^2.0.0
  flutter_widget_from_html_core: ^0.8.5+3
  infinite_scroll_pagination: ^3.2.0
  image: ^4.0.6
  permission_handler: ^10.2.0
  open_file:
    git:
      url: https://github.com/crazecoder/open_file
  shared_preferences: ^2.1.0
  extended_image: ^7.0.2
  webview_flutter: ^3.0.4
  # flutter_image_compress: ^2.0.2
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^14.0.0+2
  html: ^0.15.3
  google_fonts: ^4.0.4
  chewie: ^1.5.0
  audio_waveforms: ^0.1.5+1

  line_icons: ^2.0.1
  emoji_picker_flutter: ^1.3.1
  scrollable_positioned_list: ^0.3.4
  faker: ^2.0.0
  flutter_sound: ^9.2.13
  syncfusion_flutter_pdfviewer: ^20.3.56
  device_info_plus: ^8.0.0
  timelines: ^0.1.0
  flutter_typeahead: ^4.6.0
  matrix_gesture_detector: 0.2.0-nullsafety.1
  like_button: ^2.0.5
  miniplayer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"
  very_good_analysis: ^3.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/images/
    - assets/sounds/
    - assets/images_and_video.png
    - assets/camera_menu.png
    - assets/target_menu.png
    - assets/target_in_post.png
    - assets/gif.png
    - assets/target.png
    - assets/live_video.png
    - assets/bg_color.png
    - assets/icons/
    - assets/icon/
    - assets/reaction/
    - assets/post_media.svg
    - assets/target.svg
    - assets/win.svg
    - assets/chat.svg
    - assets/Plus.svg
    - assets/Watch.svg
    - assets/WatchFC.svg
    - assets/home.svg
    - assets/HomeFC.svg
    - assets/notification.svg
    - assets/blood.svg
    - assets/blood.png
    - assets/event.svg
    - assets/friend.svg
    - assets/Groups_1.svg
    - assets/Grow.svg
    - assets/job.svg
    - assets/learnspace.svg
    - assets/Maket.svg
    - assets/moment_menu.png
    - assets/music.svg
    - assets/Page.svg
    - assets/saved.svg
    - assets/story.svg
    - assets/ChatDM.svg
    - assets/NotiDM.svg
    - assets/Live.svg
    - assets/post_background.png
    - assets/live_event.png
    - assets/camera.png
    - assets/LogoEmso.svg
    - assets/loading.gif
    - assets/IconCoin.svg
    - assets/disc.png
    - assets/grey.png
    - assets/Payment.svg
    - assets/MomentFC.png
    - assets/MomentDM_1.png
    - assets/MomentLM.png
    - assets/MomentMenu.png
    - assets/Chat_3.png
    - assets/MarketLM.png
    - assets/MarketDM.png
    - assets/MarketFC.png
    - assets/Plus_2.png
    - assets/wow-emo-2.gif
    - assets/Noti/Noti.png
    - assets/Noti/Friend.png
    - assets/Noti/watch.png
    - assets/Noti/event.png
    - assets/Noti/moment.png
    - assets/Noti/Page.png
    - assets/Noti/group.png
    - assets/Noti/post.png
    - assets/Noti/comment.png
    - assets/Noti/livestream.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
