// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1P7yXUjZ42KHXQAdYnLCGOFroxBGYaUk',
    appId: '1:352503968807:web:09db5c575f64d44944ca02',
    messagingSenderId: '352503968807',
    projectId: 'push-notification-95768',
    authDomain: 'push-notification-95768.firebaseapp.com',
    storageBucket: 'push-notification-95768.appspot.com',
    measurementId: 'G-2FJVYY4WF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzN0kU5-1nxbGl7ED_wUP_Ktfo0Iyn1Ys',
    appId: '1:352503968807:android:2b86416fb27bcd6244ca02',
    messagingSenderId: '352503968807',
    projectId: 'push-notification-95768',
    storageBucket: 'push-notification-95768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8k5MHztia8Hpcg0tu_zxy4xUnNtLreao',
    appId: '1:352503968807:ios:eb88579e4275147044ca02',
    messagingSenderId: '352503968807',
    projectId: 'push-notification-95768',
    storageBucket: 'push-notification-95768.appspot.com',
    iosClientId: '352503968807-khj1q5qh4e8kb00u49llpfeu1bs722e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNetworkAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8k5MHztia8Hpcg0tu_zxy4xUnNtLreao',
    appId: '1:352503968807:ios:eb88579e4275147044ca02',
    messagingSenderId: '352503968807',
    projectId: 'push-notification-95768',
    storageBucket: 'push-notification-95768.appspot.com',
    iosClientId: '352503968807-khj1q5qh4e8kb00u49llpfeu1bs722e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNetworkAppMobile',
  );
}
